parameters:

    profiler.class: ganja.plugin.profiler.Profiler
    profiler.storage.class: ganja.plugin.profiler.storage.ListStorage
    profiler.listener.class: ganja.plugin.profiler.listener.ProfilerListener

    dummy.collector.class: ganja.plugin.profiler.collector.DummyCollector

services:

    profiler:
        class: %profiler.class%
        arguments: [ storage: @profiler.storage ]

    profiler.storage:
        class: %profiler.storage.class%

    profiler.listener:
        class: %profiler.listener.class%
        arguments: [ profiler: @profiler ]

    dummy.collector:
        class: %dummy.collector.class%

    profiler.controller:
        class: %profiler.controller.class%
        arguments: [ storage: @profiler.storage ]