parameters:

    profiler.class: ganja.plugin.profiler.Profiler
    profiler.storage.class: ganja.plugin.profiler.storage.ListStorage
    profiler.listener.class: ganja.plugin.profiler.listener.ProfilerListener

    dummy.collector.class: ganja.plugin.profiler.collector.DummyCollector

    controller.profiler.class: ganja.plugin.profiler.controller.ProfilerController

services:

    profiler:
        class: profiler.class
        arguments: { storage: $profiler.storage }

    profiler.storage:
        class: profiler.storage.class

    profiler.listener:
        class: profiler.listener.class
        arguments: { profiler: $profiler }
        tags:
            - { name 'listener', event: 'event.response', method: 'onResponse' }

    dummy.collector:
        class: dummy.collector.class

    controller.profiler:
        class: controller.profiler.class
        arguments: { storage: $profiler.storage }